<a href="https://colab.research.google.com/github/Wizako-01/Automated-Stress-Detection-from-Social-Media/blob/main/Mental_health_project_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# Download Dreaddit directly from Kaggle into Colab
!pip -q install kagglehub

import kagglehub
import os

# Download dataset
path = kagglehub.dataset_download("ruchi798/stress-analysis-in-social-media")

print("Dataset downloaded successfully!")
print("Location:", path)

# Show the files in the dataset
print("\nFiles in dataset:")
for file in os.listdir(path):
    print("-", file)

Downloading to /root/.cache/kagglehub/datasets/ruchi798/stress-analysis-in-social-media/1.archive...

100%|██████████| 1.31M/1.31M [00:00<00:00, 101MB/s]

Extracting files...
Dataset downloaded successfully!
Location: /root/.cache/kagglehub/datasets/ruchi798/stress-analysis-in-social-media/versions/1

Files in dataset:
- dreaddit-train.csv
- dreaddit-test.csv

In [3]:
import pandas as pd
import os

# File locations
train_path = os.path.join(path, "dreaddit-train.csv")
test_path = os.path.join(path, "dreaddit-test.csv")

# Load the datasets
train_df = pd.read_csv(train_path)
test_df = pd.read_csv(test_path)

# Basic information
print("TRAINING SET")
print("Shape:", train_df.shape)
print("\nColumns:")
print(train_df.columns.tolist())

print("\n" + "="*60)

print("TEST SET")
print("Shape:", test_df.shape)
print("\nColumns:")
print(test_df.columns.tolist())

print("\n" + "="*60)

# Show first 5 records
print("\nFirst 5 training records:")
display(train_df.head())

# Check labels
print("\nLabel distribution:")
print(train_df["label"].value_counts())
print("\nLabel proportions:")
print(train_df["label"].value_counts(normalize=True))

TRAINING SET
Shape: (2838, 116)

Columns:
['subreddit', 'post_id', 'sentence_range', 'text', 'id', 'label', 'confidence', 'social_timestamp', 'social_karma', 'syntax_ari', 'lex_liwc_WC', 'lex_liwc_Analytic', 'lex_liwc_Clout', 'lex_liwc_Authentic', 'lex_liwc_Tone', 'lex_liwc_WPS', 'lex_liwc_Sixltr', 'lex_liwc_Dic', 'lex_liwc_function', 'lex_liwc_pronoun', 'lex_liwc_ppron', 'lex_liwc_i', 'lex_liwc_we', 'lex_liwc_you', 'lex_liwc_shehe', 'lex_liwc_they', 'lex_liwc_ipron', 'lex_liwc_article', 'lex_liwc_prep', 'lex_liwc_auxverb', 'lex_liwc_adverb', 'lex_liwc_conj', 'lex_liwc_negate', 'lex_liwc_verb', 'lex_liwc_adj', 'lex_liwc_compare', 'lex_liwc_interrog', 'lex_liwc_number', 'lex_liwc_quant', 'lex_liwc_affect', 'lex_liwc_posemo', 'lex_liwc_negemo', 'lex_liwc_anx', 'lex_liwc_anger', 'lex_liwc_sad', 'lex_liwc_social', 'lex_liwc_family', 'lex_liwc_friend', 'lex_liwc_female', 'lex_liwc_male', 'lex_liwc_cogproc', 'lex_liwc_insight', 'lex_liwc_cause', 'lex_liwc_discrep', 'lex_liwc_tentat', 'lex_liwc_certain', 'lex_liwc_differ', 'lex_liwc_percept', 'lex_liwc_see', 'lex_liwc_hear', 'lex_liwc_feel', 'lex_liwc_bio', 'lex_liwc_body', 'lex_liwc_health', 'lex_liwc_sexual', 'lex_liwc_ingest', 'lex_liwc_drives', 'lex_liwc_affiliation', 'lex_liwc_achieve', 'lex_liwc_power', 'lex_liwc_reward', 'lex_liwc_risk', 'lex_liwc_focuspast', 'lex_liwc_focuspresent', 'lex_liwc_focusfuture', 'lex_liwc_relativ', 'lex_liwc_motion', 'lex_liwc_space', 'lex_liwc_time', 'lex_liwc_work', 'lex_liwc_leisure', 'lex_liwc_home', 'lex_liwc_money', 'lex_liwc_relig', 'lex_liwc_death', 'lex_liwc_informal', 'lex_liwc_swear', 'lex_liwc_netspeak', 'lex_liwc_assent', 'lex_liwc_nonflu', 'lex_liwc_filler', 'lex_liwc_AllPunc', 'lex_liwc_Period', 'lex_liwc_Comma', 'lex_liwc_Colon', 'lex_liwc_SemiC', 'lex_liwc_QMark', 'lex_liwc_Exclam', 'lex_liwc_Dash', 'lex_liwc_Quote', 'lex_liwc_Apostro', 'lex_liwc_Parenth', 'lex_liwc_OtherP', 'lex_dal_max_pleasantness', 'lex_dal_max_activation', 'lex_dal_max_imagery', 'lex_dal_min_pleasantness', 'lex_dal_min_activation', 'lex_dal_min_imagery', 'lex_dal_avg_activation', 'lex_dal_avg_imagery', 'lex_dal_avg_pleasantness', 'social_upvote_ratio', 'social_num_comments', 'syntax_fk_grade', 'sentiment']

============================================================
TEST SET
Shape: (715, 116)

Columns:
['id', 'subreddit', 'post_id', 'sentence_range', 'text', 'label', 'confidence', 'social_timestamp', 'social_karma', 'syntax_ari', 'lex_liwc_WC', 'lex_liwc_Analytic', 'lex_liwc_Clout', 'lex_liwc_Authentic', 'lex_liwc_Tone', 'lex_liwc_WPS', 'lex_liwc_Sixltr', 'lex_liwc_Dic', 'lex_liwc_function', 'lex_liwc_pronoun', 'lex_liwc_ppron', 'lex_liwc_i', 'lex_liwc_we', 'lex_liwc_you', 'lex_liwc_shehe', 'lex_liwc_they', 'lex_liwc_ipron', 'lex_liwc_article', 'lex_liwc_prep', 'lex_liwc_auxverb', 'lex_liwc_adverb', 'lex_liwc_conj', 'lex_liwc_negate', 'lex_liwc_verb', 'lex_liwc_adj', 'lex_liwc_compare', 'lex_liwc_interrog', 'lex_liwc_number', 'lex_liwc_quant', 'lex_liwc_affect', 'lex_liwc_posemo', 'lex_liwc_negemo', 'lex_liwc_anx', 'lex_liwc_anger', 'lex_liwc_sad', 'lex_liwc_social', 'lex_liwc_family', 'lex_liwc_friend', 'lex_liwc_female', 'lex_liwc_male', 'lex_liwc_cogproc', 'lex_liwc_insight', 'lex_liwc_cause', 'lex_liwc_discrep', 'lex_liwc_tentat', 'lex_liwc_certain', 'lex_liwc_differ', 'lex_liwc_percept', 'lex_liwc_see', 'lex_liwc_hear', 'lex_liwc_feel', 'lex_liwc_bio', 'lex_liwc_body', 'lex_liwc_health', 'lex_liwc_sexual', 'lex_liwc_ingest', 'lex_liwc_drives', 'lex_liwc_affiliation', 'lex_liwc_achieve', 'lex_liwc_power', 'lex_liwc_reward', 'lex_liwc_risk', 'lex_liwc_focuspast', 'lex_liwc_focuspresent', 'lex_liwc_focusfuture', 'lex_liwc_relativ', 'lex_liwc_motion', 'lex_liwc_space', 'lex_liwc_time', 'lex_liwc_work', 'lex_liwc_leisure', 'lex_liwc_home', 'lex_liwc_money', 'lex_liwc_relig', 'lex_liwc_death', 'lex_liwc_informal', 'lex_liwc_swear', 'lex_liwc_netspeak', 'lex_liwc_assent', 'lex_liwc_nonflu', 'lex_liwc_filler', 'lex_liwc_AllPunc', 'lex_liwc_Period', 'lex_liwc_Comma', 'lex_liwc_Colon', 'lex_liwc_SemiC', 'lex_liwc_QMark', 'lex_liwc_Exclam', 'lex_liwc_Dash', 'lex_liwc_Quote', 'lex_liwc_Apostro', 'lex_liwc_Parenth', 'lex_liwc_OtherP', 'lex_dal_max_pleasantness', 'lex_dal_max_activation', 'lex_dal_max_imagery', 'lex_dal_min_pleasantness', 'lex_dal_min_activation', 'lex_dal_min_imagery', 'lex_dal_avg_activation', 'lex_dal_avg_imagery', 'lex_dal_avg_pleasantness', 'social_upvote_ratio', 'social_num_comments', 'syntax_fk_grade', 'sentiment']

============================================================

First 5 training records:

,subreddit,post_id,sentence_range,text,id,label,confidence,social_timestamp,social_karma,syntax_ari,...,lex_dal_min_pleasantness,lex_dal_min_activation,lex_dal_min_imagery,lex_dal_avg_activation,lex_dal_avg_imagery,lex_dal_avg_pleasantness,social_upvote_ratio,social_num_comments,syntax_fk_grade,sentiment
0,ptsd,8601tu,"(15, 20)","He said he had not felt that way before, sugge...",33181,1,0.8,1521614353,5,1.806818,...,1.000,1.1250,1.0,1.77000,1.52211,1.89556,0.86,1,3.253573,-0.002742
1,assistance,8lbrx9,"(0, 5)","Hey there r/assistance, Not sure if this is th...",2606,0,1.0,1527009817,4,9.429737,...,1.125,1.0000,1.0,1.69586,1.62045,1.88919,0.65,2,8.828316,0.292857
2,ptsd,9ch1zh,"(15, 20)",My mom then hit me with the newspaper and it s...,38816,1,0.8,1535935605,2,7.769821,...,1.000,1.1429,1.0,1.83088,1.58108,1.85828,0.67,0,7.841667,0.011894
3,relationships,7rorpp,"[5, 10]","until i met my new boyfriend, he is amazing, h...",239,1,0.6,1516429555,0,2.667798,...,1.000,1.1250,1.0,1.75356,1.52114,1.98848,0.50,5,4.104027,0.141671
4,survivorsofabuse,9p2gbc,"[0, 5]",October is Domestic Violence Awareness Month a...,1421,1,0.8,1539809005,24,7.554238,...,1.000,1.1250,1.0,1.77644,1.64872,1.81456,1.00,1,7.910952,-0.204167

Label distribution:
label
1    1488
0    1350
Name: count, dtype: int64

Label proportions:
label
1    0.524313
0    0.475687
Name: proportion, dtype: float64

In [4]:
# ============================================================
# DREADDIT MENTAL-HEALTH AI PROJECT
# Stress Detection: Classical NLP vs Feature Fusion vs Transformer
# ============================================================

# -----------------------------
# 1. INSTALL REQUIRED PACKAGES
# -----------------------------
!pip -q install transformers datasets accelerate scikit-learn

# -----------------------------
# 2. IMPORT LIBRARIES
# -----------------------------
import os
import numpy as np
import pandas as pd
import torch

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    classification_report,
    confusion_matrix
)
from scipy.sparse import hstack, csr_matrix

from transformers import (
    AutoTokenizer,
    AutoModelForSequenceClassification,
    TrainingArguments,
    Trainer
)

# -----------------------------
# 3. DOWNLOAD DATASET
# -----------------------------
import kagglehub

path = kagglehub.dataset_download(
    "ruchi798/stress-analysis-in-social-media"
)

train_path = os.path.join(path, "dreaddit-train.csv")
test_path = os.path.join(path, "dreaddit-test.csv")

train_df = pd.read_csv(train_path)
test_df = pd.read_csv(test_path)

print("=" * 70)
print("DATASET LOADED")
print("=" * 70)
print("Training samples:", len(train_df))
print("Test samples:", len(test_df))
print("Training columns:", train_df.shape[1])
print("Test columns:", test_df.shape[1])

# -----------------------------
# 4. CLEAN TEXT
# -----------------------------
train_df["text"] = train_df["text"].fillna("").astype(str)
test_df["text"] = test_df["text"].fillna("").astype(str)

y_train = train_df["label"].astype(int)
y_test = test_df["label"].astype(int)

X_train_text = train_df["text"]
X_test_text = test_df["text"]

print("\nLabel distribution:")
print(y_train.value_counts())

# ============================================================
# MODEL 1: TF-IDF + LOGISTIC REGRESSION
# ============================================================

print("\n" + "=" * 70)
print("MODEL 1: TF-IDF + LOGISTIC REGRESSION")
print("=" * 70)

tfidf = TfidfVectorizer(
    max_features=30000,
    ngram_range=(1, 2),
    min_df=2,
    sublinear_tf=True
)

X_train_tfidf = tfidf.fit_transform(X_train_text)
X_test_tfidf = tfidf.transform(X_test_text)

model_tfidf = LogisticRegression(
    max_iter=1000,
    class_weight="balanced",
    random_state=42
)

model_tfidf.fit(X_train_tfidf, y_train)

pred_tfidf = model_tfidf.predict(X_test_tfidf)
prob_tfidf = model_tfidf.predict_proba(X_test_tfidf)[:, 1]

results = []

results.append({
    "Model": "TF-IDF + Logistic Regression",
    "Accuracy": accuracy_score(y_test, pred_tfidf),
    "Precision": precision_score(y_test, pred_tfidf),
    "Recall": recall_score(y_test, pred_tfidf),
    "F1": f1_score(y_test, pred_tfidf),
    "AUROC": roc_auc_score(y_test, prob_tfidf)
})

print(classification_report(y_test, pred_tfidf))
print("Confusion matrix:")
print(confusion_matrix(y_test, pred_tfidf))

# ============================================================
# MODEL 2: TF-IDF + LINGUISTIC/SOCIAL FEATURES
# ============================================================

print("\n" + "=" * 70)
print("MODEL 2: TF-IDF + LINGUISTIC/SOCIAL FEATURE FUSION")
print("=" * 70)

# Select numeric features that are available before prediction.
# We intentionally exclude:
# - label
# - post_id
# - id
# - subreddit
# - timestamp
# - text
#
# This prevents obvious identifier/subreddit leakage.

exclude_columns = [
    "label",
    "post_id",
    "id",
    "subreddit",
    "text",
    "social_timestamp"
]

numeric_features = [
    col for col in train_df.columns
    if col not in exclude_columns
    and pd.api.types.is_numeric_dtype(train_df[col])
]

print("Number of additional numeric features:", len(numeric_features))

# Replace missing values
X_train_numeric = train_df[numeric_features].replace(
    [np.inf, -np.inf], np.nan
).fillna(0)

X_test_numeric = test_df[numeric_features].replace(
    [np.inf, -np.inf], np.nan
).fillna(0)

# Standardize numerical features
scaler = StandardScaler()

X_train_num_scaled = scaler.fit_transform(X_train_numeric)
X_test_num_scaled = scaler.transform(X_test_numeric)

# Convert to sparse matrices
X_train_num_sparse = csr_matrix(X_train_num_scaled)
X_test_num_sparse = csr_matrix(X_test_num_scaled)

# Combine TF-IDF + linguistic/social features
X_train_fusion = hstack([
    X_train_tfidf,
    X_train_num_sparse
])

X_test_fusion = hstack([
    X_test_tfidf,
    X_test_num_sparse
])

model_fusion = LogisticRegression(
    max_iter=1000,
    class_weight="balanced",
    random_state=42
)

model_fusion.fit(X_train_fusion, y_train)

pred_fusion = model_fusion.predict(X_test_fusion)
prob_fusion = model_fusion.predict_proba(X_test_fusion)[:, 1]

results.append({
    "Model": "TF-IDF + Linguistic/Social Features",
    "Accuracy": accuracy_score(y_test, pred_fusion),
    "Precision": precision_score(y_test, pred_fusion),
    "Recall": recall_score(y_test, pred_fusion),
    "F1": f1_score(y_test, pred_fusion),
    "AUROC": roc_auc_score(y_test, prob_fusion)
})

print(classification_report(y_test, pred_fusion))
print("Confusion matrix:")
print(confusion_matrix(y_test, pred_fusion))

# ============================================================
# MODEL 3: DISTILBERT
# ============================================================

print("\n" + "=" * 70)
print("MODEL 3: DISTILBERT")
print("=" * 70)

# Check GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
print("Device:", device)

# Use a compact transformer so it can train efficiently in Colab
MODEL_NAME = "distilbert-base-uncased"

tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)

# Create Hugging Face datasets
from datasets import Dataset

train_hf = Dataset.from_pandas(
    train_df[["text", "label"]],
    preserve_index=False
)

test_hf = Dataset.from_pandas(
    test_df[["text", "label"]],
    preserve_index=False
)

def tokenize_function(examples):
    return tokenizer(
        examples["text"],
        truncation=True,
        padding="max_length",
        max_length=256
    )

train_tokenized = train_hf.map(
    tokenize_function,
    batched=True
)

test_tokenized = test_hf.map(
    tokenize_function,
    batched=True
)

train_tokenized = train_tokenized.remove_columns(["text"])
test_tokenized = test_tokenized.remove_columns(["text"])

# Rename label column if needed
if "label" not in train_tokenized.column_names:
    train_tokenized = train_tokenized.rename_column(
        "labels", "label"
    )

if "label" not in test_tokenized.column_names:
    test_tokenized = test_tokenized.rename_column(
        "labels", "label"
    )

train_tokenized.set_format("torch")
test_tokenized.set_format("torch")

bert_model = AutoModelForSequenceClassification.from_pretrained(
    MODEL_NAME,
    num_labels=2
)

def compute_metrics(eval_pred):
    logits, labels = eval_pred

    predictions = np.argmax(logits, axis=-1)

    # Softmax for AUROC
    probabilities = torch.softmax(
        torch.tensor(logits),
        dim=1
    ).numpy()[:, 1]

    return {
        "accuracy": accuracy_score(labels, predictions),
        "precision": precision_score(
            labels, predictions, zero_division=0
        ),
        "recall": recall_score(
            labels, predictions, zero_division=0
        ),
        "f1": f1_score(
            labels, predictions, zero_division=0
        ),
        "auroc": roc_auc_score(
            labels, probabilities
        )
    }

training_args = TrainingArguments(
    output_dir="./distilbert_dreaddit",
    eval_strategy="epoch",
    save_strategy="no",
    learning_rate=2e-5,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=32,
    num_train_epochs=3,
    weight_decay=0.01,
    logging_steps=50,
    report_to="none",
    fp16=torch.cuda.is_available()
)

trainer = Trainer(
    model=bert_model,
    args=training_args,
    train_dataset=train_tokenized,
    eval_dataset=test_tokenized,
    processing_class=tokenizer,
    compute_metrics=compute_metrics
)

trainer.train()

bert_results = trainer.evaluate()

results.append({
    "Model": "DistilBERT",
    "Accuracy": bert_results["eval_accuracy"],
    "Precision": bert_results["eval_precision"],
    "Recall": bert_results["eval_recall"],
    "F1": bert_results["eval_f1"],
    "AUROC": bert_results["eval_auroc"]
})

# ============================================================
# FINAL COMPARISON
# ============================================================

print("\n" + "=" * 70)
print("FINAL MODEL COMPARISON")
print("=" * 70)

results_df = pd.DataFrame(results)

for column in [
    "Accuracy",
    "Precision",
    "Recall",
    "F1",
    "AUROC"
]:
    results_df[column] = results_df[column].round(4)

display(
    results_df.sort_values(
        "AUROC",
        ascending=False
    ).reset_index(drop=True)
)

# ============================================================
# SAVE RESULTS
# ============================================================

results_df.to_csv(
    "/content/dreaddit_model_comparison.csv",
    index=False
)

print("\nResults saved to:")
print("/content/dreaddit_model_comparison.csv")

print("\nTraining experiment completed.")

======================================================================
DATASET LOADED
======================================================================
Training samples: 2838
Test samples: 715
Training columns: 116
Test columns: 116

Label distribution:
label
1    1488
0    1350
Name: count, dtype: int64

======================================================================
MODEL 1: TF-IDF + LOGISTIC REGRESSION
======================================================================
              precision    recall  f1-score   support

           0       0.73      0.67      0.70       346
           1       0.71      0.76      0.74       369

    accuracy                           0.72       715
   macro avg       0.72      0.72      0.72       715
weighted avg       0.72      0.72      0.72       715

Confusion matrix:
[[231 115]
 [ 87 282]]

======================================================================
MODEL 2: TF-IDF + LINGUISTIC/SOCIAL FEATURE FUSION
======================================================================
Number of additional numeric features: 109
              precision    recall  f1-score   support

           0       0.76      0.75      0.76       346
           1       0.77      0.78      0.78       369

    accuracy                           0.77       715
   macro avg       0.77      0.77      0.77       715
weighted avg       0.77      0.77      0.77       715

Confusion matrix:
[[259  87]
 [ 80 289]]

======================================================================
MODEL 3: DISTILBERT
======================================================================
Device: cpu

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config.json:   0%|          | 0.00/483 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

Map:   0%|          | 0/2838 [00:00<?, ? examples/s]

Map:   0%|          | 0/715 [00:00<?, ? examples/s]

model.safetensors: reconstructing file:   0%|          |  0.00B /  268MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

[transformers] DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_transform.bias    | UNEXPECTED |
vocab_layer_norm.bias   | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
vocab_projector.bias    | UNEXPECTED |
vocab_layer_norm.weight | UNEXPECTED |
pre_classifier.bias     | MISSING    |
classifier.weight       | MISSING    |
classifier.bias         | MISSING    |
pre_classifier.weight   | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

ImportError: cannot import name 'VideoReader' from 'torchvision.io' (/usr/local/lib/python3.12/dist-packages/torchvision/io/__init__.py)

In [1]:
!pip -q install --upgrade torch torchvision transformers datasets accelerate

import torch

print("PyTorch:", torch.__version__)
print("CUDA available:", torch.cuda.is_available())

if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))
else:
    print("WARNING: GPU is not enabled.")

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 526.6/526.6 MB 3.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 366.2/366.2 MB 4.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 170.1/170.1 MB 6.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 206.0/206.0 MB 5.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.4/60.4 MB 11.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 197.7/197.7 MB 6.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 423.1/423.1 MB 3.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.7/10.7 MB 34.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 90.2/90.2 MB 9.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.2/2.2 MB 60.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 214.1/214.1 MB 5.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 32.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 59.5/59.5 MB 11.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 200.9/200.9 MB 6.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 145.9/145.9 MB 7.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 148.0/148.0 kB 11.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.7/7.7 MB 86.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.7/11.7 MB 94.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 559.1/559.1 kB 31.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.7/6.7 MB 93.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.1/50.1 MB 13.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 818.2/818.2 kB 34.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.7/40.7 MB 16.2 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
ipython 7.34.0 requires jedi>=0.16, which is not installed.
libraft-cu12 26.2.0 requires cuda-toolkit[cublas,curand,cusolver,cusparse]==12.*, but you have cuda-toolkit 13.0.3.0 which is incompatible.
libcuml-cu12 26.2.0 requires cuda-toolkit[cublas,cufft,curand,cusolver,cusparse]==12.*, but you have cuda-toolkit 13.0.3.0 which is incompatible.
cudf-cu12 26.2.1 requires cuda-toolkit[nvcc,nvrtc]==12.*, but you have cuda-toolkit 13.0.3.0 which is incompatible.
cuda-python 12.9.7 requires cuda-bindings~=12.9.7, but you have cuda-bindings 13.3.1 which is incompatible.
cuml-cu12 26.2.0 requires cuda-toolkit[cublas,cufft,curand,cusolver,cusparse]==12.*, but you have cuda-toolkit 13.0.3.0 which is incompatible.
libcuvs-cu12 26.2.0 requires cuda-toolkit[cublas,curand,cusolver,cusparse]==12.*, but you have cuda-toolkit 13.0.3.0 which is incompatible.
PyTorch: 2.13.0+cu130
CUDA available: True
GPU: Tesla T4

In [2]:
# ============================================================
# DREADDIT — DISTILBERT STRESS CLASSIFICATION
# ============================================================

import os
import numpy as np
import pandas as pd
import torch

from datasets import Dataset
from transformers import (
    AutoTokenizer,
    AutoModelForSequenceClassification,
    TrainingArguments,
    Trainer
)

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    confusion_matrix,
    classification_report
)

# ------------------------------------------------------------
# 1. CHECK GPU
# ------------------------------------------------------------

print("PyTorch:", torch.__version__)
print("CUDA available:", torch.cuda.is_available())

if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))
else:
    raise RuntimeError("GPU is not available. Enable T4 GPU in Colab.")

# ------------------------------------------------------------
# 2. DOWNLOAD / LOAD DREADDIT
# ------------------------------------------------------------

import kagglehub

path = kagglehub.dataset_download(
    "ruchi798/stress-analysis-in-social-media"
)

train_df = pd.read_csv(
    os.path.join(path, "dreaddit-train.csv")
)

test_df = pd.read_csv(
    os.path.join(path, "dreaddit-test.csv")
)

train_df["text"] = train_df["text"].fillna("").astype(str)
test_df["text"] = test_df["text"].fillna("").astype(str)

print("\nDataset:")
print("Training:", train_df.shape)
print("Testing:", test_df.shape)

# ------------------------------------------------------------
# 3. CREATE HUGGING FACE DATASETS
# ------------------------------------------------------------

train_hf = Dataset.from_pandas(
    train_df[["text", "label"]],
    preserve_index=False
)

test_hf = Dataset.from_pandas(
    test_df[["text", "label"]],
    preserve_index=False
)

# ------------------------------------------------------------
# 4. TOKENIZER
# ------------------------------------------------------------

MODEL_NAME = "distilbert-base-uncased"

tokenizer = AutoTokenizer.from_pretrained(
    MODEL_NAME
)

def tokenize(batch):
    return tokenizer(
        batch["text"],
        padding="max_length",
        truncation=True,
        max_length=256
    )

train_tokenized = train_hf.map(
    tokenize,
    batched=True,
    remove_columns=["text"]
)

test_tokenized = test_hf.map(
    tokenize,
    batched=True,
    remove_columns=["text"]
)

# ------------------------------------------------------------
# 5. MODEL
# ------------------------------------------------------------

model = AutoModelForSequenceClassification.from_pretrained(
    MODEL_NAME,
    num_labels=2
)

# ------------------------------------------------------------
# 6. METRICS
# ------------------------------------------------------------

def compute_metrics(eval_pred):

    logits, labels = eval_pred

    predictions = np.argmax(logits, axis=-1)

    # Stable softmax
    exp_logits = np.exp(
        logits - np.max(logits, axis=1, keepdims=True)
    )

    probabilities = (
        exp_logits[:, 1] /
        exp_logits.sum(axis=1)
    )

    return {
        "accuracy": accuracy_score(
            labels, predictions
        ),
        "precision": precision_score(
            labels,
            predictions,
            zero_division=0
        ),
        "recall": recall_score(
            labels,
            predictions,
            zero_division=0
        ),
        "f1": f1_score(
            labels,
            predictions,
            zero_division=0
        ),
        "auroc": roc_auc_score(
            labels,
            probabilities
        )
    }

# ------------------------------------------------------------
# 7. TRAINING CONFIGURATION
# ------------------------------------------------------------

training_args = TrainingArguments(
    output_dir="/content/dreaddit_distilbert",

    eval_strategy="epoch",

    save_strategy="no",

    learning_rate=2e-5,

    per_device_train_batch_size=16,

    per_device_eval_batch_size=32,

    num_train_epochs=3,

    weight_decay=0.01,

    logging_steps=50,

    report_to="none",

    fp16=True,

    seed=42
)

# ------------------------------------------------------------
# 8. TRAINER
# ------------------------------------------------------------

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_tokenized,
    eval_dataset=test_tokenized,
    processing_class=tokenizer,
    compute_metrics=compute_metrics
)

# ------------------------------------------------------------
# 9. TRAIN
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("STARTING DISTILBERT TRAINING")
print("=" * 70)

trainer.train()

# ------------------------------------------------------------
# 10. FINAL EVALUATION
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("FINAL DISTILBERT RESULTS")
print("=" * 70)

evaluation = trainer.evaluate()

for key, value in evaluation.items():
    if isinstance(value, float):
        print(f"{key}: {value:.4f}")
    else:
        print(f"{key}: {value}")

# ------------------------------------------------------------
# 11. PREDICTIONS + CONFUSION MATRIX
# ------------------------------------------------------------

pred_output = trainer.predict(test_tokenized)

logits = pred_output.predictions
labels = pred_output.label_ids

predictions = np.argmax(logits, axis=-1)

exp_logits = np.exp(
    logits - np.max(logits, axis=1, keepdims=True)
)

probabilities = (
    exp_logits[:, 1] /
    exp_logits.sum(axis=1)
)

print("\nClassification Report:")
print(
    classification_report(
        labels,
        predictions,
        target_names=[
            "Non-Stress",
            "Stress"
        ]
    )
)

print("\nConfusion Matrix:")
print(
    confusion_matrix(
        labels,
        predictions
    )
)

# ------------------------------------------------------------
# 12. SAVE DISTILBERT RESULTS
# ------------------------------------------------------------

distilbert_results = pd.DataFrame({
    "Model": ["DistilBERT"],
    "Accuracy": [
        accuracy_score(labels, predictions)
    ],
    "Precision": [
        precision_score(
            labels,
            predictions,
            zero_division=0
        )
    ],
    "Recall": [
        recall_score(
            labels,
            predictions,
            zero_division=0
        )
    ],
    "F1": [
        f1_score(
            labels,
            predictions,
            zero_division=0
        )
    ],
    "AUROC": [
        roc_auc_score(
            labels,
            probabilities
        )
    ]
})

display(
    distilbert_results.round(4)
)

distilbert_results.to_csv(
    "/content/dreaddit_distilbert_results.csv",
    index=False
)

print("\nResults saved to:")
print("/content/dreaddit_distilbert_results.csv")

ModuleNotFoundError: Could not import module 'TrainingArguments'. Are this object's requirements defined correctly?

In [3]:
# ============================================================
# DREADDIT MENTAL-HEALTH AI PROJECT
# Complete pipeline:
# 1. Download dataset
# 2. Load and inspect data
# 3. TF-IDF baseline
# 4. TF-IDF + linguistic/social feature fusion
# 5. DistilBERT
# 6. Compare all models
# ============================================================

# ------------------------------------------------------------
# 1. INSTALL ONLY THE REQUIRED NLP PACKAGES
#    DO NOT upgrade torch / torchvision / torchaudio
# ------------------------------------------------------------

!pip -q install -U transformers datasets accelerate kagglehub

# ------------------------------------------------------------
# 2. IMPORT LIBRARIES
# ------------------------------------------------------------

import os
import numpy as np
import pandas as pd
import torch

from scipy.sparse import hstack, csr_matrix

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    confusion_matrix,
    classification_report
)

from datasets import Dataset
from transformers import (
    AutoTokenizer,
    AutoModelForSequenceClassification,
    TrainingArguments,
    Trainer
)

# ------------------------------------------------------------
# 3. CHECK THE COLAB ENVIRONMENT
# ------------------------------------------------------------

print("=" * 70)
print("COLAB ENVIRONMENT")
print("=" * 70)

print("PyTorch:", torch.__version__)
print("CUDA available:", torch.cuda.is_available())

if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))
else:
    print("WARNING: GPU unavailable.")
    print("The transformer model will run on CPU and may take longer.")

# ------------------------------------------------------------
# 4. DOWNLOAD DREADDIT DIRECTLY FROM KAGGLE
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("DOWNLOADING DREADDIT")
print("=" * 70)

import kagglehub

path = kagglehub.dataset_download(
    "ruchi798/stress-analysis-in-social-media"
)

print("Dataset location:")
print(path)

print("\nFiles:")
for f in os.listdir(path):
    print("-", f)

# ------------------------------------------------------------
# 5. LOAD DATA
# ------------------------------------------------------------

train_path = os.path.join(
    path,
    "dreaddit-train.csv"
)

test_path = os.path.join(
    path,
    "dreaddit-test.csv"
)

train_df = pd.read_csv(train_path)
test_df = pd.read_csv(test_path)

train_df["text"] = (
    train_df["text"]
    .fillna("")
    .astype(str)
)

test_df["text"] = (
    test_df["text"]
    .fillna("")
    .astype(str)
)

print("\n" + "=" * 70)
print("DATASET")
print("=" * 70)

print("Training samples:", len(train_df))
print("Testing samples:", len(test_df))

print("\nTraining shape:", train_df.shape)
print("Testing shape:", test_df.shape)

print("\nLabel distribution:")
print(train_df["label"].value_counts())

print("\nLabel proportions:")
print(
    train_df["label"]
    .value_counts(normalize=True)
    .round(4)
)

# ------------------------------------------------------------
# 6. TRAIN/TEST VARIABLES
# ------------------------------------------------------------

X_train_text = train_df["text"]
X_test_text = test_df["text"]

y_train = train_df["label"].astype(int)
y_test = test_df["label"].astype(int)

# ============================================================
# MODEL 1
# TF-IDF + LOGISTIC REGRESSION
# ============================================================

print("\n" + "=" * 70)
print("MODEL 1: TF-IDF + LOGISTIC REGRESSION")
print("=" * 70)

tfidf = TfidfVectorizer(
    max_features=30000,
    ngram_range=(1, 2),
    min_df=2,
    sublinear_tf=True
)

X_train_tfidf = tfidf.fit_transform(
    X_train_text
)

X_test_tfidf = tfidf.transform(
    X_test_text
)

print(
    "TF-IDF training matrix:",
    X_train_tfidf.shape
)

model_tfidf = LogisticRegression(
    max_iter=1000,
    class_weight="balanced",
    random_state=42
)

model_tfidf.fit(
    X_train_tfidf,
    y_train
)

pred_tfidf = model_tfidf.predict(
    X_test_tfidf
)

prob_tfidf = model_tfidf.predict_proba(
    X_test_tfidf
)[:, 1]

tfidf_results = {
    "Model": "TF-IDF + Logistic Regression",
    "Accuracy": accuracy_score(
        y_test,
        pred_tfidf
    ),
    "Precision": precision_score(
        y_test,
        pred_tfidf,
        zero_division=0
    ),
    "Recall": recall_score(
        y_test,
        pred_tfidf,
        zero_division=0
    ),
    "F1": f1_score(
        y_test,
        pred_tfidf,
        zero_division=0
    ),
    "AUROC": roc_auc_score(
        y_test,
        prob_tfidf
    )
}

print("\nClassification report:")
print(
    classification_report(
        y_test,
        pred_tfidf,
        target_names=[
            "Non-Stress",
            "Stress"
        ]
    )
)

print("Confusion matrix:")
print(
    confusion_matrix(
        y_test,
        pred_tfidf
    )
)

# ============================================================
# MODEL 2
# TF-IDF + LINGUISTIC/SOCIAL FEATURES
# ============================================================

print("\n" + "=" * 70)
print("MODEL 2: TF-IDF + LINGUISTIC/SOCIAL FEATURES")
print("=" * 70)

# Exclude identifiers, label, raw text,
# subreddit and timestamp.
#
# We exclude subreddit because using it directly could
# encourage the model to learn community identity rather
# than stress-related language.

exclude_columns = [
    "label",
    "post_id",
    "id",
    "subreddit",
    "text",
    "social_timestamp"
]

numeric_features = [
    col
    for col in train_df.columns
    if (
        col not in exclude_columns
        and pd.api.types.is_numeric_dtype(
            train_df[col]
        )
    )
]

print(
    "Number of numeric features:",
    len(numeric_features)
)

X_train_numeric = (
    train_df[numeric_features]
    .replace([np.inf, -np.inf], np.nan)
    .fillna(0)
)

X_test_numeric = (
    test_df[numeric_features]
    .replace([np.inf, -np.inf], np.nan)
    .fillna(0)
)

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(
    X_train_numeric
)

X_test_scaled = scaler.transform(
    X_test_numeric
)

X_train_numeric_sparse = csr_matrix(
    X_train_scaled
)

X_test_numeric_sparse = csr_matrix(
    X_test_scaled
)

X_train_fusion = hstack([
    X_train_tfidf,
    X_train_numeric_sparse
])

X_test_fusion = hstack([
    X_test_tfidf,
    X_test_numeric_sparse
])

print(
    "Fusion training matrix:",
    X_train_fusion.shape
)

model_fusion = LogisticRegression(
    max_iter=1500,
    class_weight="balanced",
    random_state=42
)

model_fusion.fit(
    X_train_fusion,
    y_train
)

pred_fusion = model_fusion.predict(
    X_test_fusion
)

prob_fusion = model_fusion.predict_proba(
    X_test_fusion
)[:, 1]

fusion_results = {
    "Model": "TF-IDF + Linguistic/Social Features",
    "Accuracy": accuracy_score(
        y_test,
        pred_fusion
    ),
    "Precision": precision_score(
        y_test,
        pred_fusion,
        zero_division=0
    ),
    "Recall": recall_score(
        y_test,
        pred_fusion,
        zero_division=0
    ),
    "F1": f1_score(
        y_test,
        pred_fusion,
        zero_division=0
    ),
    "AUROC": roc_auc_score(
        y_test,
        prob_fusion
    )
}

print("\nClassification report:")
print(
    classification_report(
        y_test,
        pred_fusion,
        target_names=[
            "Non-Stress",
            "Stress"
        ]
    )
)

print("Confusion matrix:")
print(
    confusion_matrix(
        y_test,
        pred_fusion
    )
)

# ============================================================
# MODEL 3
# DISTILBERT
# ============================================================

print("\n" + "=" * 70)
print("MODEL 3: DISTILBERT")
print("=" * 70)

MODEL_NAME = "distilbert-base-uncased"

# ------------------------------------------------------------
# Convert pandas to Hugging Face Dataset
# ------------------------------------------------------------

train_hf = Dataset.from_pandas(
    train_df[["text", "label"]],
    preserve_index=False
)

test_hf = Dataset.from_pandas(
    test_df[["text", "label"]],
    preserve_index=False
)

# ------------------------------------------------------------
# Tokenizer
# ------------------------------------------------------------

tokenizer = AutoTokenizer.from_pretrained(
    MODEL_NAME
)

def tokenize_function(examples):

    return tokenizer(
        examples["text"],
        truncation=True,
        padding="max_length",
        max_length=256
    )

print("Tokenizing training data...")

train_tokenized = train_hf.map(
    tokenize_function,
    batched=True,
    remove_columns=["text"]
)

print("Tokenizing test data...")

test_tokenized = test_hf.map(
    tokenize_function,
    batched=True,
    remove_columns=["text"]
)

# ------------------------------------------------------------
# Model
# ------------------------------------------------------------

print("Loading DistilBERT...")

bert_model = (
    AutoModelForSequenceClassification
    .from_pretrained(
        MODEL_NAME,
        num_labels=2
    )
)

# ------------------------------------------------------------
# Metrics
# ------------------------------------------------------------

def compute_metrics(eval_pred):

    logits, labels = eval_pred

    predictions = np.argmax(
        logits,
        axis=-1
    )

    # Numerically stable softmax
    shifted = (
        logits -
        np.max(
            logits,
            axis=1,
            keepdims=True
        )
    )

    exp_logits = np.exp(
        shifted
    )

    probabilities = (
        exp_logits[:, 1] /
        exp_logits.sum(
            axis=1
        )
    )

    return {
        "accuracy": accuracy_score(
            labels,
            predictions
        ),

        "precision": precision_score(
            labels,
            predictions,
            zero_division=0
        ),

        "recall": recall_score(
            labels,
            predictions,
            zero_division=0
        ),

        "f1": f1_score(
            labels,
            predictions,
            zero_division=0
        ),

        "auroc": roc_auc_score(
            labels,
            probabilities
        )
    }

# ------------------------------------------------------------
# Training arguments
# ------------------------------------------------------------

training_args = TrainingArguments(
    output_dir="/content/dreaddit_distilbert",

    eval_strategy="epoch",

    save_strategy="no",

    learning_rate=2e-5,

    per_device_train_batch_size=16,

    per_device_eval_batch_size=32,

    num_train_epochs=3,

    weight_decay=0.01,

    logging_steps=50,

    report_to="none",

    fp16=torch.cuda.is_available(),

    seed=42
)

# ------------------------------------------------------------
# Trainer
# ------------------------------------------------------------

trainer = Trainer(
    model=bert_model,

    args=training_args,

    train_dataset=train_tokenized,

    eval_dataset=test_tokenized,

    processing_class=tokenizer,

    compute_metrics=compute_metrics
)

# ------------------------------------------------------------
# Train
# ------------------------------------------------------------

print("\nStarting DistilBERT training...")

trainer.train()

# ------------------------------------------------------------
# Evaluate
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("DISTILBERT FINAL EVALUATION")
print("=" * 70)

bert_eval = trainer.evaluate()

# ------------------------------------------------------------
# Predictions
# ------------------------------------------------------------

bert_predictions = trainer.predict(
    test_tokenized
)

bert_logits = (
    bert_predictions.predictions
)

bert_labels = (
    bert_predictions.label_ids
)

bert_pred_class = np.argmax(
    bert_logits,
    axis=-1
)

shifted = (
    bert_logits -
    np.max(
        bert_logits,
        axis=1,
        keepdims=True
    )
)

exp_logits = np.exp(
    shifted
)

bert_probabilities = (
    exp_logits[:, 1] /
    exp_logits.sum(
        axis=1
    )
)

print("\nClassification report:")

print(
    classification_report(
        bert_labels,
        bert_pred_class,
        target_names=[
            "Non-Stress",
            "Stress"
        ]
    )
)

print("\nConfusion matrix:")

print(
    confusion_matrix(
        bert_labels,
        bert_pred_class
    )
)

bert_results = {
    "Model": "DistilBERT",

    "Accuracy": accuracy_score(
        bert_labels,
        bert_pred_class
    ),

    "Precision": precision_score(
        bert_labels,
        bert_pred_class,
        zero_division=0
    ),

    "Recall": recall_score(
        bert_labels,
        bert_pred_class,
        zero_division=0
    ),

    "F1": f1_score(
        bert_labels,
        bert_pred_class,
        zero_division=0
    ),

    "AUROC": roc_auc_score(
        bert_labels,
        bert_probabilities
    )
}

# ============================================================
# FINAL MODEL COMPARISON
# ============================================================

print("\n" + "=" * 70)
print("FINAL MODEL COMPARISON")
print("=" * 70)

results_df = pd.DataFrame([
    tfidf_results,
    fusion_results,
    bert_results
])

metric_columns = [
    "Accuracy",
    "Precision",
    "Recall",
    "F1",
    "AUROC"
]

results_df[metric_columns] = (
    results_df[metric_columns]
    .round(4)
)

display(
    results_df.sort_values(
        "AUROC",
        ascending=False
    ).reset_index(drop=True)
)

# ------------------------------------------------------------
# Save results
# ------------------------------------------------------------

results_df.to_csv(
    "/content/dreaddit_model_comparison.csv",
    index=False
)

print(
    "\nResults saved to:"
)

print(
    "/content/dreaddit_model_comparison.csv"
)

print("\n" + "=" * 70)
print("EXPERIMENT COMPLETE")
print("=" * 70)

ModuleNotFoundError: Could not import module 'TrainingArguments'. Are this object's requirements defined correctly?

In [1]:
# ============================================================
# DREADDIT STRESS DETECTION
# COMPLETE CLASSICAL ML EXPERIMENT
# ============================================================

# 1. INSTALL ONLY WHAT WE NEED
!pip -q install kagglehub

# ============================================================
# 2. IMPORT LIBRARIES
# ============================================================

import os
import numpy as np
import pandas as pd

from scipy.sparse import hstack, csr_matrix

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.svm import LinearSVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    confusion_matrix,
    classification_report
)

import kagglehub

# ============================================================
# 3. DOWNLOAD DATASET DIRECTLY FROM KAGGLE
# ============================================================

print("=" * 70)
print("DOWNLOADING DREADDIT DATASET")
print("=" * 70)

path = kagglehub.dataset_download(
    "ruchi798/stress-analysis-in-social-media"
)

print("Dataset location:")
print(path)

print("\nFiles found:")
for file in os.listdir(path):
    print("-", file)

# ============================================================
# 4. LOAD TRAINING AND TEST DATA
# ============================================================

train_df = pd.read_csv(
    os.path.join(path, "dreaddit-train.csv")
)

test_df = pd.read_csv(
    os.path.join(path, "dreaddit-test.csv")
)

# Clean text
train_df["text"] = (
    train_df["text"]
    .fillna("")
    .astype(str)
)

test_df["text"] = (
    test_df["text"]
    .fillna("")
    .astype(str)
)

y_train = train_df["label"].astype(int)
y_test = test_df["label"].astype(int)

print("\n" + "=" * 70)
print("DATASET INFORMATION")
print("=" * 70)

print("Training samples:", len(train_df))
print("Test samples:", len(test_df))
print("Training columns:", len(train_df.columns))

print("\nTraining label distribution:")
print(y_train.value_counts())

# ============================================================
# 5. TF-IDF TEXT REPRESENTATION
# ============================================================

print("\n" + "=" * 70)
print("CREATING TF-IDF FEATURES")
print("=" * 70)

tfidf = TfidfVectorizer(
    max_features=30000,
    ngram_range=(1, 2),
    min_df=2,
    sublinear_tf=True
)

X_train_tfidf = tfidf.fit_transform(
    train_df["text"]
)

X_test_tfidf = tfidf.transform(
    test_df["text"]
)

print("TF-IDF training matrix:", X_train_tfidf.shape)
print("TF-IDF test matrix:", X_test_tfidf.shape)

# ============================================================
# RESULTS STORAGE
# ============================================================

results = []

# ============================================================
# MODEL 1
# TF-IDF + LOGISTIC REGRESSION
# ============================================================

print("\n" + "=" * 70)
print("MODEL 1: TF-IDF + LOGISTIC REGRESSION")
print("=" * 70)

model_lr = LogisticRegression(
    max_iter=1500,
    class_weight="balanced",
    random_state=42
)

model_lr.fit(
    X_train_tfidf,
    y_train
)

pred_lr = model_lr.predict(
    X_test_tfidf
)

prob_lr = model_lr.predict_proba(
    X_test_tfidf
)[:, 1]

results.append({
    "Model": "TF-IDF + Logistic Regression",
    "Accuracy": accuracy_score(y_test, pred_lr),
    "Precision": precision_score(y_test, pred_lr, zero_division=0),
    "Recall": recall_score(y_test, pred_lr, zero_division=0),
    "F1": f1_score(y_test, pred_lr, zero_division=0),
    "AUROC": roc_auc_score(y_test, prob_lr)
})

print(
    classification_report(
        y_test,
        pred_lr,
        target_names=["Non-Stress", "Stress"]
    )
)

print("Confusion Matrix:")
print(confusion_matrix(y_test, pred_lr))

# ============================================================
# MODEL 2
# TF-IDF + LINEAR SVM
# ============================================================

print("\n" + "=" * 70)
print("MODEL 2: TF-IDF + LINEAR SVM")
print("=" * 70)

model_svm = LinearSVC(
    C=1.0,
    class_weight="balanced",
    random_state=42
)

model_svm.fit(
    X_train_tfidf,
    y_train
)

pred_svm = model_svm.predict(
    X_test_tfidf
)

svm_score = model_svm.decision_function(
    X_test_tfidf
)

results.append({
    "Model": "TF-IDF + Linear SVM",
    "Accuracy": accuracy_score(y_test, pred_svm),
    "Precision": precision_score(y_test, pred_svm, zero_division=0),
    "Recall": recall_score(y_test, pred_svm, zero_division=0),
    "F1": f1_score(y_test, pred_svm, zero_division=0),
    "AUROC": roc_auc_score(y_test, svm_score)
})

print(
    classification_report(
        y_test,
        pred_svm,
        target_names=["Non-Stress", "Stress"]
    )
)

print("Confusion Matrix:")
print(confusion_matrix(y_test, pred_svm))

# ============================================================
# 6. SELECT STRUCTURED FEATURES
# ============================================================

print("\n" + "=" * 70)
print("PREPARING LINGUISTIC AND SOCIAL FEATURES")
print("=" * 70)

# Exclude identifiers and variables that could introduce
# obvious leakage or simply identify the Reddit community.

exclude_columns = [
    "label",
    "post_id",
    "id",
    "subreddit",
    "text",
    "social_timestamp"
]

numeric_features = [
    column
    for column in train_df.columns
    if (
        column not in exclude_columns
        and pd.api.types.is_numeric_dtype(
            train_df[column]
        )
    )
]

print(
    "Number of structured features:",
    len(numeric_features)
)

# Handle missing/infinite values

X_train_numeric = (
    train_df[numeric_features]
    .replace([np.inf, -np.inf], np.nan)
    .fillna(0)
)

X_test_numeric = (
    test_df[numeric_features]
    .replace([np.inf, -np.inf], np.nan)
    .fillna(0)
)

# Standardize for linear models

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(
    X_train_numeric
)

X_test_scaled = scaler.transform(
    X_test_numeric
)

# ============================================================
# MODEL 3
# STRUCTURED FEATURES ONLY
# ============================================================

print("\n" + "=" * 70)
print("MODEL 3: LINGUISTIC/SOCIAL FEATURES ONLY")
print("=" * 70)

model_structured = LogisticRegression(
    max_iter=1500,
    class_weight="balanced",
    random_state=42
)

model_structured.fit(
    X_train_scaled,
    y_train
)

pred_structured = model_structured.predict(
    X_test_scaled
)

prob_structured = (
    model_structured
    .predict_proba(X_test_scaled)[:, 1]
)

results.append({
    "Model": "Linguistic/Social Features Only",
    "Accuracy": accuracy_score(y_test, pred_structured),
    "Precision": precision_score(y_test, pred_structured, zero_division=0),
    "Recall": recall_score(y_test, pred_structured, zero_division=0),
    "F1": f1_score(y_test, pred_structured, zero_division=0),
    "AUROC": roc_auc_score(y_test, prob_structured)
})

print(
    classification_report(
        y_test,
        pred_structured,
        target_names=["Non-Stress", "Stress"]
    )
)

# ============================================================
# MODEL 4
# TF-IDF + STRUCTURED FEATURES
# ============================================================

print("\n" + "=" * 70)
print("MODEL 4: TF-IDF + LINGUISTIC/SOCIAL FEATURES")
print("=" * 70)

X_train_fusion = hstack([
    X_train_tfidf,
    csr_matrix(X_train_scaled)
])

X_test_fusion = hstack([
    X_test_tfidf,
    csr_matrix(X_test_scaled)
])

model_fusion = LogisticRegression(
    max_iter=1500,
    class_weight="balanced",
    random_state=42
)

model_fusion.fit(
    X_train_fusion,
    y_train
)

pred_fusion = model_fusion.predict(
    X_test_fusion
)

prob_fusion = (
    model_fusion
    .predict_proba(X_test_fusion)[:, 1]
)

results.append({
    "Model": "TF-IDF + Linguistic/Social Features",
    "Accuracy": accuracy_score(y_test, pred_fusion),
    "Precision": precision_score(y_test, pred_fusion, zero_division=0),
    "Recall": recall_score(y_test, pred_fusion, zero_division=0),
    "F1": f1_score(y_test, pred_fusion, zero_division=0),
    "AUROC": roc_auc_score(y_test, prob_fusion)
})

print(
    classification_report(
        y_test,
        pred_fusion,
        target_names=["Non-Stress", "Stress"]
    )
)

print("Confusion Matrix:")
print(confusion_matrix(y_test, pred_fusion))

# ============================================================
# MODEL 5
# RANDOM FOREST — STRUCTURED FEATURES
# ============================================================

print("\n" + "=" * 70)
print("MODEL 5: RANDOM FOREST — STRUCTURED FEATURES")
print("=" * 70)

model_rf = RandomForestClassifier(
    n_estimators=400,
    min_samples_leaf=2,
    class_weight="balanced",
    random_state=42,
    n_jobs=-1
)

model_rf.fit(
    X_train_numeric,
    y_train
)

pred_rf = model_rf.predict(
    X_test_numeric
)

prob_rf = model_rf.predict_proba(
    X_test_numeric
)[:, 1]

results.append({
    "Model": "Random Forest — Structured Features",
    "Accuracy": accuracy_score(y_test, pred_rf),
    "Precision": precision_score(y_test, pred_rf, zero_division=0),
    "Recall": recall_score(y_test, pred_rf, zero_division=0),
    "F1": f1_score(y_test, pred_rf, zero_division=0),
    "AUROC": roc_auc_score(y_test, prob_rf)
})

print(
    classification_report(
        y_test,
        pred_rf,
        target_names=["Non-Stress", "Stress"]
    )
)

print("Confusion Matrix:")
print(confusion_matrix(y_test, pred_rf))

# ============================================================
# 7. FINAL MODEL COMPARISON
# ============================================================

print("\n" + "=" * 70)
print("FINAL MODEL COMPARISON")
print("=" * 70)

results_df = pd.DataFrame(results)

metric_columns = [
    "Accuracy",
    "Precision",
    "Recall",
    "F1",
    "AUROC"
]

results_df[metric_columns] = (
    results_df[metric_columns]
    .round(4)
)

results_df = (
    results_df
    .sort_values("AUROC", ascending=False)
    .reset_index(drop=True)
)

display(results_df)

# ============================================================
# 8. FEATURE IMPORTANCE
# ============================================================

print("\n" + "=" * 70)
print("TOP 20 STRUCTURED FEATURES — RANDOM FOREST")
print("=" * 70)

feature_importance = pd.DataFrame({
    "Feature": numeric_features,
    "Importance": model_rf.feature_importances_
})

feature_importance = (
    feature_importance
    .sort_values("Importance", ascending=False)
    .reset_index(drop=True)
)

display(
    feature_importance.head(20)
)

# ============================================================
# 9. SAVE RESULTS
# ============================================================

results_df.to_csv(
    "/content/dreaddit_model_comparison.csv",
    index=False
)

feature_importance.to_csv(
    "/content/dreaddit_feature_importance.csv",
    index=False
)

print("\nFiles saved:")
print("/content/dreaddit_model_comparison.csv")
print("/content/dreaddit_feature_importance.csv")

# ============================================================
# 10. SUBREDDIT DISTRIBUTION
# ============================================================

print("\n" + "=" * 70)
print("SUBREDDIT / LABEL DISTRIBUTION")
print("=" * 70)

subreddit_distribution = pd.crosstab(
    train_df["subreddit"],
    train_df["label"],
    normalize="index"
).round(3)

display(subreddit_distribution)

print("\nSample count by subreddit:")

display(
    train_df["subreddit"]
    .value_counts()
)

print("\n" + "=" * 70)
print("EXPERIMENT COMPLETE")
print("=" * 70)

======================================================================
DOWNLOADING DREADDIT DATASET
======================================================================
Downloading to /root/.cache/kagglehub/datasets/ruchi798/stress-analysis-in-social-media/1.archive...

100%|██████████| 1.31M/1.31M [00:00<00:00, 106MB/s]

Extracting files...
Dataset location:
/root/.cache/kagglehub/datasets/ruchi798/stress-analysis-in-social-media/versions/1

Files found:
- dreaddit-test.csv
- dreaddit-train.csv

======================================================================
DATASET INFORMATION
======================================================================
Training samples: 2838
Test samples: 715
Training columns: 116

Training label distribution:
label
1    1488
0    1350
Name: count, dtype: int64

======================================================================
CREATING TF-IDF FEATURES
======================================================================
TF-IDF training matrix: (2838, 30000)
TF-IDF test matrix: (715, 30000)

======================================================================
MODEL 1: TF-IDF + LOGISTIC REGRESSION
======================================================================
              precision    recall  f1-score   support

  Non-Stress       0.72      0.67      0.69       346
      Stress       0.71      0.76      0.73       369

    accuracy                           0.72       715
   macro avg       0.72      0.71      0.71       715
weighted avg       0.72      0.72      0.72       715

Confusion Matrix:
[[231 115]
 [ 88 281]]

======================================================================
MODEL 2: TF-IDF + LINEAR SVM
======================================================================
              precision    recall  f1-score   support

  Non-Stress       0.73      0.69      0.71       346
      Stress       0.72      0.76      0.74       369

    accuracy                           0.73       715
   macro avg       0.73      0.73      0.73       715
weighted avg       0.73      0.73      0.73       715

Confusion Matrix:
[[239 107]
 [ 88 281]]

======================================================================
PREPARING LINGUISTIC AND SOCIAL FEATURES
======================================================================
Number of structured features: 109

======================================================================
MODEL 3: LINGUISTIC/SOCIAL FEATURES ONLY
======================================================================
              precision    recall  f1-score   support

  Non-Stress       0.74      0.74      0.74       346
      Stress       0.75      0.76      0.76       369

    accuracy                           0.75       715
   macro avg       0.75      0.75      0.75       715
weighted avg       0.75      0.75      0.75       715


======================================================================
MODEL 4: TF-IDF + LINGUISTIC/SOCIAL FEATURES
======================================================================
              precision    recall  f1-score   support

  Non-Stress       0.76      0.75      0.76       346
      Stress       0.77      0.78      0.78       369

    accuracy                           0.77       715
   macro avg       0.77      0.77      0.77       715
weighted avg       0.77      0.77      0.77       715

Confusion Matrix:
[[259  87]
 [ 80 289]]

======================================================================
MODEL 5: RANDOM FOREST — STRUCTURED FEATURES
======================================================================
              precision    recall  f1-score   support

  Non-Stress       0.76      0.70      0.73       346
      Stress       0.74      0.79      0.76       369

    accuracy                           0.75       715
   macro avg       0.75      0.75      0.75       715
weighted avg       0.75      0.75      0.75       715

Confusion Matrix:
[[242 104]
 [ 77 292]]

======================================================================
FINAL MODEL COMPARISON
======================================================================

,Model,Accuracy,Precision,Recall,F1,AUROC
0,TF-IDF + Linguistic/Social Features,0.7664,0.7686,0.7832,0.7758,0.8458
1,Linguistic/Social Features Only,0.7469,0.7541,0.7561,0.7551,0.8373
2,Random Forest — Structured Features,0.7469,0.7374,0.7913,0.7634,0.8361
3,TF-IDF + Logistic Regression,0.7161,0.7096,0.7615,0.7346,0.8205
4,TF-IDF + Linear SVM,0.7273,0.7242,0.7615,0.7424,0.8171

======================================================================
TOP 20 STRUCTURED FEATURES — RANDOM FOREST
======================================================================

                     Feature  Importance
0              lex_liwc_Tone    0.056990
1            lex_liwc_negemo    0.052262
2                 lex_liwc_i    0.045497
3             lex_liwc_Clout    0.043575
4                  sentiment    0.030299
5            lex_liwc_social    0.021213
6         lex_liwc_Authentic    0.020159
7   lex_dal_min_pleasantness    0.019320
8            lex_liwc_posemo    0.019006
9      lex_liwc_focuspresent    0.018248
10              lex_liwc_Dic    0.017883
11              lex_liwc_anx    0.017396
12         lex_liwc_function    0.015301
13         lex_liwc_Analytic    0.014047
14           lex_liwc_affect    0.013511
15            lex_liwc_ppron    0.013027
16        lex_liwc_focuspast    0.012565
17                confidence    0.012145
18            lex_liwc_anger    0.012077
19    lex_dal_avg_activation    0.012051

Files saved:
/content/dreaddit_model_comparison.csv
/content/dreaddit_feature_importance.csv

======================================================================
SUBREDDIT / LABEL DISTRIBUTION
======================================================================

label                 0      1
subreddit
almosthomeless    0.412  0.588
anxiety           0.342  0.658
assistance        0.637  0.363
domesticviolence  0.361  0.639
food_pantry       0.622  0.378
homeless          0.625  0.375
ptsd              0.432  0.568
relationships     0.553  0.447
stress            0.453  0.547
survivorsofabuse  0.543  0.457

Sample count by subreddit:

subreddit
ptsd                584
relationships       552
anxiety             503
domesticviolence    316
assistance          289
survivorsofabuse    245
homeless            168
almosthomeless       80
stress               64
food_pantry          37
Name: count, dtype: int64

======================================================================
EXPERIMENT COMPLETE
======================================================================

In [2]:
# ============================================================
# DREADDIT — FEATURE ABLATION STUDY
# ============================================================
#
# Question:
# Which categories of linguistic/social features contribute
# most to stress detection?
#
# We compare:
# 1. Text only
# 2. Affective/psychological features
# 3. Cognitive/language features
# 4. Social/relationship features
# 5. Temporal/focus features
# 6. Social-media engagement features
# 7. All structured features
#
# ============================================================

import os
import numpy as np
import pandas as pd

from scipy.sparse import hstack, csr_matrix

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score
)

import kagglehub


# ============================================================
# 1. LOAD DATASET
# ============================================================

print("=" * 70)
print("LOADING DREADDIT")
print("=" * 70)

path = kagglehub.dataset_download(
    "ruchi798/stress-analysis-in-social-media"
)

train_df = pd.read_csv(
    os.path.join(path, "dreaddit-train.csv")
)

test_df = pd.read_csv(
    os.path.join(path, "dreaddit-test.csv")
)

train_df["text"] = (
    train_df["text"]
    .fillna("")
    .astype(str)
)

test_df["text"] = (
    test_df["text"]
    .fillna("")
    .astype(str)
)

y_train = train_df["label"].astype(int)
y_test = test_df["label"].astype(int)


# ============================================================
# 2. TF-IDF
# ============================================================

print("\nCreating TF-IDF representation...")

tfidf = TfidfVectorizer(
    max_features=30000,
    ngram_range=(1, 2),
    min_df=2,
    sublinear_tf=True
)

X_train_text = tfidf.fit_transform(
    train_df["text"]
)

X_test_text = tfidf.transform(
    test_df["text"]
)


# ============================================================
# 3. IDENTIFY ALL STRUCTURED FEATURES
# ============================================================

exclude = [
    "label",
    "post_id",
    "id",
    "subreddit",
    "text",
    "social_timestamp"
]

all_structured = [
    c
    for c in train_df.columns
    if (
        c not in exclude
        and pd.api.types.is_numeric_dtype(
            train_df[c]
        )
    )
]

print(
    "Total structured features:",
    len(all_structured)
)


# ============================================================
# 4. DEFINE FEATURE GROUPS
# ============================================================

# ------------------------------------------------------------
# AFFECTIVE / PSYCHOLOGICAL FEATURES
# ------------------------------------------------------------

affective_keywords = [
    "affect",
    "posemo",
    "negemo",
    "anx",
    "anger",
    "sad",
    "tone",
    "sentiment",
    "health",
    "death",
    "risk",
    "feel"
]


# ------------------------------------------------------------
# COGNITIVE / LANGUAGE FEATURES
# ------------------------------------------------------------

cognitive_keywords = [
    "cogproc",
    "insight",
    "cause",
    "discrep",
    "tentat",
    "certain",
    "differ",
    "analytic",
    "clout",
    "authentic",
    "dic",
    "function",
    "pronoun",
    "ppron",
    "i"
]


# ------------------------------------------------------------
# SOCIAL / RELATIONSHIP FEATURES
# ------------------------------------------------------------

social_keywords = [
    "social",
    "family",
    "friend",
    "female",
    "male",
    "affiliation",
    "achieve",
    "power",
    "reward"
]


# ------------------------------------------------------------
# TEMPORAL / ATTENTION FEATURES
# ------------------------------------------------------------

temporal_keywords = [
    "focuspast",
    "focuspresent",
    "focusfuture",
    "time",
    "space",
    "motion"
]


# ------------------------------------------------------------
# SOCIAL-MEDIA ENGAGEMENT
# ------------------------------------------------------------

engagement_features = [
    "social_karma",
    "social_upvote_ratio",
    "social_num_comments"
]


# ============================================================
# 5. FUNCTION FOR KEYWORD-BASED GROUPING
# ============================================================

def keyword_group(
    columns,
    keywords
):

    selected = []

    for column in columns:

        column_lower = column.lower()

        if any(
            keyword.lower() in column_lower
            for keyword in keywords
        ):
            selected.append(column)

    return sorted(
        list(set(selected))
    )


affective_features = keyword_group(
    all_structured,
    affective_keywords
)

cognitive_features = keyword_group(
    all_structured,
    cognitive_keywords
)

social_features = keyword_group(
    all_structured,
    social_keywords
)

temporal_features = keyword_group(
    all_structured,
    temporal_keywords
)

engagement_features = [
    f
    for f in engagement_features
    if f in all_structured
]


# ============================================================
# 6. PRINT FEATURE GROUPS
# ============================================================

print("\n" + "=" * 70)
print("FEATURE GROUPS")
print("=" * 70)

print(
    "\nAffective/Psychological:",
    len(affective_features)
)

print(
    affective_features
)

print(
    "\nCognitive/Language:",
    len(cognitive_features)
)

print(
    cognitive_features
)

print(
    "\nSocial/Relationship:",
    len(social_features)
)

print(
    social_features
)

print(
    "\nTemporal/Attention:",
    len(temporal_features)
)

print(
    temporal_features
)

print(
    "\nSocial-media engagement:",
    len(engagement_features)
)

print(
    engagement_features
)


# ============================================================
# 7. STANDARDIZE ALL STRUCTURED DATA
# ============================================================

structured_scaler = StandardScaler()

X_train_all_structured = (
    train_df[all_structured]
    .replace(
        [np.inf, -np.inf],
        np.nan
    )
    .fillna(0)
)

X_test_all_structured = (
    test_df[all_structured]
    .replace(
        [np.inf, -np.inf],
        np.nan
    )
    .fillna(0)
)

X_train_all_scaled = (
    structured_scaler
    .fit_transform(
        X_train_all_structured
    )
)

X_test_all_scaled = (
    structured_scaler
    .transform(
        X_test_all_structured
    )
)


# ============================================================
# 8. FUNCTION TO TRAIN AND EVALUATE
# ============================================================

def evaluate_feature_set(
    name,
    feature_columns
):

    print(
        "\nRunning:",
        name
    )

    # --------------------------------------------------------
    # No structured features
    # --------------------------------------------------------

    if len(feature_columns) == 0:

        X_train = X_train_text

        X_test = X_test_text

    else:

        # Get positions of selected columns
        positions = [
            all_structured.index(c)
            for c in feature_columns
        ]

        X_train_structured = (
            X_train_all_scaled[
                :,
                positions
            ]
        )

        X_test_structured = (
            X_test_all_scaled[
                :,
                positions
            ]
        )

        X_train = hstack([
            X_train_text,
            csr_matrix(
                X_train_structured
            )
        ])

        X_test = hstack([
            X_test_text,
            csr_matrix(
                X_test_structured
            )
        ])

    # --------------------------------------------------------
    # Model
    # --------------------------------------------------------

    model = LogisticRegression(
        max_iter=1500,
        class_weight="balanced",
        random_state=42
    )

    model.fit(
        X_train,
        y_train
    )

    predictions = model.predict(
        X_test
    )

    probabilities = (
        model
        .predict_proba(
            X_test
        )[:, 1]
    )

    return {
        "Feature Set": name,

        "Number of Features":
            len(feature_columns),

        "Accuracy":
            accuracy_score(
                y_test,
                predictions
            ),

        "Precision":
            precision_score(
                y_test,
                predictions,
                zero_division=0
            ),

        "Recall":
            recall_score(
                y_test,
                predictions,
                zero_division=0
            ),

        "F1":
            f1_score(
                y_test,
                predictions,
                zero_division=0
            ),

        "AUROC":
            roc_auc_score(
                y_test,
                probabilities
            )
    }


# ============================================================
# 9. RUN ABLATION EXPERIMENTS
# ============================================================

ablation_results = []


# ------------------------------------------------------------
# BASELINE — TEXT ONLY
# ------------------------------------------------------------

ablation_results.append(
    evaluate_feature_set(
        "Text only (TF-IDF)",
        []
    )
)


# ------------------------------------------------------------
# AFFECTIVE
# ------------------------------------------------------------

ablation_results.append(
    evaluate_feature_set(
        "Affective/Psychological",
        affective_features
    )
)


# ------------------------------------------------------------
# COGNITIVE
# ------------------------------------------------------------

ablation_results.append(
    evaluate_feature_set(
        "Cognitive/Language",
        cognitive_features
    )
)


# ------------------------------------------------------------
# SOCIAL
# ------------------------------------------------------------

ablation_results.append(
    evaluate_feature_set(
        "Social/Relationship",
        social_features
    )
)


# ------------------------------------------------------------
# TEMPORAL
# ------------------------------------------------------------

ablation_results.append(
    evaluate_feature_set(
        "Temporal/Attention",
        temporal_features
    )
)


# ------------------------------------------------------------
# ENGAGEMENT
# ------------------------------------------------------------

ablation_results.append(
    evaluate_feature_set(
        "Social-media Engagement",
        engagement_features
    )
)


# ------------------------------------------------------------
# ALL STRUCTURED FEATURES
# ------------------------------------------------------------

ablation_results.append(
    evaluate_feature_set(
        "All Structured Features",
        all_structured
    )
)


# ============================================================
# 10. COMBINATION EXPERIMENTS
# ============================================================

affective_cognitive = sorted(
    list(
        set(
            affective_features +
            cognitive_features
        )
    )
)

affective_social = sorted(
    list(
        set(
            affective_features +
            social_features
        )
    )
)

affective_temporal = sorted(
    list(
        set(
            affective_features +
            temporal_features
        )
    )
)

all_psychological = sorted(
    list(
        set(
            affective_features +
            cognitive_features +
            social_features +
            temporal_features
        )
    )
)


ablation_results.append(
    evaluate_feature_set(
        "Affective + Cognitive",
        affective_cognitive
    )
)

ablation_results.append(
    evaluate_feature_set(
        "Affective + Social",
        affective_social
    )
)

ablation_results.append(
    evaluate_feature_set(
        "Affective + Temporal",
        affective_temporal
    )
)

ablation_results.append(
    evaluate_feature_set(
        "Psychological/Linguistic Combined",
        all_psychological
    )
)


# ============================================================
# 11. FINAL RESULTS
# ============================================================

print("\n" + "=" * 70)
print("FEATURE ABLATION RESULTS")
print("=" * 70)

ablation_df = pd.DataFrame(
    ablation_results
)

metrics = [
    "Accuracy",
    "Precision",
    "Recall",
    "F1",
    "AUROC"
]

ablation_df[metrics] = (
    ablation_df[metrics]
    .round(4)
)

ablation_df = (
    ablation_df
    .sort_values(
        "AUROC",
        ascending=False
    )
    .reset_index(drop=True)
)

display(
    ablation_df
)


# ============================================================
# 12. SAVE RESULTS
# ============================================================

ablation_df.to_csv(
    "/content/dreaddit_feature_ablation.csv",
    index=False
)

print(
    "\nSaved:"
)

print(
    "/content/dreaddit_feature_ablation.csv"
)


# ============================================================
# 13. CALCULATE IMPROVEMENT OVER TEXT BASELINE
# ============================================================

baseline_auroc = (
    ablation_df.loc[
        ablation_df["Feature Set"]
        == "Text only (TF-IDF)",
        "AUROC"
    ].iloc[0]
)

ablation_df["AUROC Improvement"] = (
    ablation_df["AUROC"] -
    baseline_auroc
).round(4)

print("\n" + "=" * 70)
print("IMPROVEMENT OVER TEXT-ONLY BASELINE")
print("=" * 70)

display(
    ablation_df[
        [
            "Feature Set",
            "Number of Features",
            "AUROC",
            "AUROC Improvement"
        ]
    ]
    .sort_values(
        "AUROC Improvement",
        ascending=False
    )
    .reset_index(drop=True)
)

print("\n" + "=" * 70)
print("ABLATION STUDY COMPLETE")
print("=" * 70)

======================================================================
LOADING DREADDIT
======================================================================
Using Colab cache for faster access to the 'stress-analysis-in-social-media' dataset.

Creating TF-IDF representation...
Total structured features: 109

======================================================================
FEATURE GROUPS
======================================================================

Affective/Psychological: 12
['lex_liwc_Tone', 'lex_liwc_affect', 'lex_liwc_anger', 'lex_liwc_anx', 'lex_liwc_death', 'lex_liwc_feel', 'lex_liwc_health', 'lex_liwc_negemo', 'lex_liwc_posemo', 'lex_liwc_risk', 'lex_liwc_sad', 'sentiment']

Cognitive/Language: 106
['confidence', 'lex_dal_avg_activation', 'lex_dal_avg_imagery', 'lex_dal_max_activation', 'lex_dal_max_imagery', 'lex_dal_min_activation', 'lex_dal_min_imagery', 'lex_dal_min_pleasantness', 'lex_liwc_AllPunc', 'lex_liwc_Analytic', 'lex_liwc_Apostro', 'lex_liwc_Authentic', 'lex_liwc_Clout', 'lex_liwc_Colon', 'lex_liwc_Comma', 'lex_liwc_Dash', 'lex_liwc_Dic', 'lex_liwc_Exclam', 'lex_liwc_OtherP', 'lex_liwc_Parenth', 'lex_liwc_Period', 'lex_liwc_QMark', 'lex_liwc_Quote', 'lex_liwc_SemiC', 'lex_liwc_Sixltr', 'lex_liwc_Tone', 'lex_liwc_WC', 'lex_liwc_WPS', 'lex_liwc_achieve', 'lex_liwc_adj', 'lex_liwc_adverb', 'lex_liwc_affect', 'lex_liwc_affiliation', 'lex_liwc_anger', 'lex_liwc_anx', 'lex_liwc_article', 'lex_liwc_assent', 'lex_liwc_auxverb', 'lex_liwc_bio', 'lex_liwc_body', 'lex_liwc_cause', 'lex_liwc_certain', 'lex_liwc_cogproc', 'lex_liwc_compare', 'lex_liwc_conj', 'lex_liwc_death', 'lex_liwc_differ', 'lex_liwc_discrep', 'lex_liwc_drives', 'lex_liwc_family', 'lex_liwc_feel', 'lex_liwc_female', 'lex_liwc_filler', 'lex_liwc_focusfuture', 'lex_liwc_focuspast', 'lex_liwc_focuspresent', 'lex_liwc_friend', 'lex_liwc_function', 'lex_liwc_health', 'lex_liwc_hear', 'lex_liwc_home', 'lex_liwc_i', 'lex_liwc_informal', 'lex_liwc_ingest', 'lex_liwc_insight', 'lex_liwc_interrog', 'lex_liwc_ipron', 'lex_liwc_leisure', 'lex_liwc_male', 'lex_liwc_money', 'lex_liwc_motion', 'lex_liwc_negate', 'lex_liwc_negemo', 'lex_liwc_netspeak', 'lex_liwc_nonflu', 'lex_liwc_number', 'lex_liwc_percept', 'lex_liwc_posemo', 'lex_liwc_power', 'lex_liwc_ppron', 'lex_liwc_prep', 'lex_liwc_pronoun', 'lex_liwc_quant', 'lex_liwc_relativ', 'lex_liwc_relig', 'lex_liwc_reward', 'lex_liwc_risk', 'lex_liwc_sad', 'lex_liwc_see', 'lex_liwc_sexual', 'lex_liwc_shehe', 'lex_liwc_social', 'lex_liwc_space', 'lex_liwc_swear', 'lex_liwc_tentat', 'lex_liwc_they', 'lex_liwc_time', 'lex_liwc_verb', 'lex_liwc_we', 'lex_liwc_work', 'lex_liwc_you', 'sentiment', 'social_karma', 'social_num_comments', 'social_upvote_ratio', 'syntax_ari']

Social/Relationship: 12
['lex_liwc_achieve', 'lex_liwc_affiliation', 'lex_liwc_family', 'lex_liwc_female', 'lex_liwc_friend', 'lex_liwc_male', 'lex_liwc_power', 'lex_liwc_reward', 'lex_liwc_social', 'social_karma', 'social_num_comments', 'social_upvote_ratio']

Temporal/Attention: 7
['lex_liwc_focusfuture', 'lex_liwc_focuspast', 'lex_liwc_focuspresent', 'lex_liwc_motion', 'lex_liwc_space', 'lex_liwc_time', 'sentiment']

Social-media engagement: 3
['social_karma', 'social_upvote_ratio', 'social_num_comments']

Running: Text only (TF-IDF)

Running: Affective/Psychological

Running: Cognitive/Language

Running: Social/Relationship

Running: Temporal/Attention

Running: Social-media Engagement

Running: All Structured Features

Running: Affective + Cognitive

Running: Affective + Social

Running: Affective + Temporal

Running: Psychological/Linguistic Combined

======================================================================
FEATURE ABLATION RESULTS
======================================================================

,Feature Set,Number of Features,Accuracy,Precision,Recall,F1,AUROC
0,Affective + Social,24,0.7622,0.7571,0.7940,0.7751,0.8586
1,Affective/Psychological,12,0.7692,0.7615,0.8049,0.7826,0.8581
2,Affective + Temporal,18,0.7608,0.7538,0.7967,0.7747,0.8519
3,Psychological/Linguistic Combined,106,0.7636,0.7703,0.7724,0.7713,0.8465
4,Cognitive/Language,106,0.7636,0.7703,0.7724,0.7713,0.8465
5,Affective + Cognitive,106,0.7636,0.7703,0.7724,0.7713,0.8465
6,All Structured Features,109,0.7664,0.7686,0.7832,0.7758,0.8458
7,Social-media Engagement,3,0.7427,0.7307,0.7940,0.7610,0.8250
8,Text only (TF-IDF),0,0.7161,0.7096,0.7615,0.7346,0.8205
9,Social/Relationship,12,0.7231,0.7041,0.7995,0.7487,0.8142
10,Temporal/Attention,7,0.7189,0.7165,0.7534,0.7345,0.8112

Saved:
/content/dreaddit_feature_ablation.csv

======================================================================
IMPROVEMENT OVER TEXT-ONLY BASELINE
======================================================================

,Feature Set,Number of Features,AUROC,AUROC Improvement
0,Affective + Social,24,0.8586,0.0381
1,Affective/Psychological,12,0.8581,0.0376
2,Affective + Temporal,18,0.8519,0.0314
3,Psychological/Linguistic Combined,106,0.8465,0.0260
4,Cognitive/Language,106,0.8465,0.0260
5,Affective + Cognitive,106,0.8465,0.0260
6,All Structured Features,109,0.8458,0.0253
7,Social-media Engagement,3,0.8250,0.0045
8,Text only (TF-IDF),0,0.8205,0.0000
9,Social/Relationship,12,0.8142,-0.0063
10,Temporal/Attention,7,0.8112,-0.0093

======================================================================
ABLATION STUDY COMPLETE
======================================================================

In [3]:
# ============================================================
# DREADDIT — CLEAN FEATURE ABLATION STUDY
# ============================================================
#
# Research question:
# Can affective linguistic features improve stress detection
# beyond text alone, and does social-context information add
# further predictive value?
#
# IMPORTANT:
# Feature groups are explicitly defined.
# No broad substring matching is used.
# "confidence" is excluded.
#
# ============================================================

import os
import numpy as np
import pandas as pd

from scipy.sparse import hstack, csr_matrix

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score
)

import kagglehub


# ============================================================
# 1. LOAD DATA
# ============================================================

print("=" * 70)
print("LOADING DREADDIT DATASET")
print("=" * 70)

path = kagglehub.dataset_download(
    "ruchi798/stress-analysis-in-social-media"
)

train_df = pd.read_csv(
    os.path.join(path, "dreaddit-train.csv")
)

test_df = pd.read_csv(
    os.path.join(path, "dreaddit-test.csv")
)

train_df["text"] = (
    train_df["text"]
    .fillna("")
    .astype(str)
)

test_df["text"] = (
    test_df["text"]
    .fillna("")
    .astype(str)
)

y_train = train_df["label"].astype(int)
y_test = test_df["label"].astype(int)


# ============================================================
# 2. TF-IDF TEXT FEATURES
# ============================================================

print("\nCreating TF-IDF features...")

tfidf = TfidfVectorizer(
    max_features=30000,
    ngram_range=(1, 2),
    min_df=2,
    sublinear_tf=True
)

X_train_text = tfidf.fit_transform(
    train_df["text"]
)

X_test_text = tfidf.transform(
    test_df["text"]
)

print(
    "TF-IDF shape:",
    X_train_text.shape
)


# ============================================================
# 3. EXCLUDE NON-PREDICTOR VARIABLES
# ============================================================

exclude = [
    "label",
    "post_id",
    "id",
    "subreddit",
    "text",
    "social_timestamp",
    "confidence"
]

all_structured = [
    c
    for c in train_df.columns
    if (
        c not in exclude
        and pd.api.types.is_numeric_dtype(
            train_df[c]
        )
    )
]

print(
    "\nNumber of usable structured features:",
    len(all_structured)
)


# ============================================================
# 4. EXPLICIT FEATURE GROUPS
# ============================================================

# ------------------------------------------------------------
# A. AFFECTIVE / PSYCHOLOGICAL
# ------------------------------------------------------------

affective_features = [
    "lex_liwc_Tone",
    "lex_liwc_affect",
    "lex_liwc_posemo",
    "lex_liwc_negemo",
    "lex_liwc_anx",
    "lex_liwc_anger",
    "lex_liwc_sad",
    "lex_liwc_feel",
    "lex_liwc_health",
    "lex_liwc_risk",
    "lex_liwc_death",
    "sentiment"
]


# ------------------------------------------------------------
# B. COGNITIVE / PSYCHOLINGUISTIC
# ------------------------------------------------------------

cognitive_features = [
    "lex_liwc_Analytic",
    "lex_liwc_Clout",
    "lex_liwc_Authentic",
    "lex_liwc_cogproc",
    "lex_liwc_insight",
    "lex_liwc_cause",
    "lex_liwc_discrep",
    "lex_liwc_tentat",
    "lex_liwc_certain",
    "lex_liwc_differ"
]


# ------------------------------------------------------------
# C. SELF-REFERENCE / PRONOUNS
# ------------------------------------------------------------

self_reference_features = [
    "lex_liwc_i",
    "lex_liwc_we",
    "lex_liwc_you",
    "lex_liwc_shehe",
    "lex_liwc_they",
    "lex_liwc_ppron",
    "lex_liwc_pronoun",
    "lex_liwc_ipron"
]


# ------------------------------------------------------------
# D. SOCIAL / RELATIONSHIP
# ------------------------------------------------------------

social_features = [
    "lex_liwc_social",
    "lex_liwc_family",
    "lex_liwc_friend",
    "lex_liwc_affiliation",
    "lex_liwc_female",
    "lex_liwc_male",
    "lex_liwc_power",
    "lex_liwc_reward",
    "lex_liwc_achieve"
]


# ------------------------------------------------------------
# E. TEMPORAL / ATTENTION
# ------------------------------------------------------------

temporal_features = [
    "lex_liwc_focuspast",
    "lex_liwc_focuspresent",
    "lex_liwc_focusfuture"
]


# ------------------------------------------------------------
# F. SOCIAL MEDIA ENGAGEMENT
# ------------------------------------------------------------

engagement_features = [
    "social_karma",
    "social_upvote_ratio",
    "social_num_comments"
]


# ------------------------------------------------------------
# G. BASIC LANGUAGE / SYNTAX
# ------------------------------------------------------------

language_features = [
    "lex_liwc_WC",
    "lex_liwc_WPS",
    "lex_liwc_Dic",
    "lex_liwc_function",
    "lex_liwc_pronoun",
    "lex_liwc_article",
    "lex_liwc_prep",
    "lex_liwc_auxverb",
    "lex_liwc_adverb",
    "lex_liwc_conj",
    "lex_liwc_negate",
    "lex_liwc_verb",
    "lex_liwc_adj",
    "lex_liwc_compare",
    "lex_liwc_interrog",
    "lex_liwc_number",
    "lex_liwc_quant",
    "lex_liwc_sixltr"
]

# Correct capitalization if Sixltr exists
if "lex_liwc_Sixltr" in all_structured:
    language_features[
        language_features.index("lex_liwc_sixltr")
    ] = "lex_liwc_Sixltr"


# ------------------------------------------------------------
# H. DAL LEXICAL FEATURES
# ------------------------------------------------------------

dal_features = [
    "lex_dal_max_pleasantness",
    "lex_dal_max_activation",
    "lex_dal_max_imagery",
    "lex_dal_min_pleasantness",
    "lex_dal_min_activation",
    "lex_dal_min_imagery",
    "lex_dal_avg_activation",
    "lex_dal_avg_imagery",
    "lex_dal_avg_pleasantness"
]


# ------------------------------------------------------------
# I. SYNTAX
# ------------------------------------------------------------

syntax_features = [
    "syntax_ari",
    "syntax_fk_grade"
]


# ============================================================
# 5. CLEAN FEATURE LISTS
# ============================================================

feature_groups = {

    "Affective/Psychological":
        affective_features,

    "Cognitive/Psycholinguistic":
        cognitive_features,

    "Self-Reference/Pronouns":
        self_reference_features,

    "Social/Relationship":
        social_features,

    "Temporal/Attention":
        temporal_features,

    "Social-Media Engagement":
        engagement_features,

    "Basic Language":
        language_features,

    "DAL Lexical":
        dal_features,

    "Syntax":
        syntax_features
}


# Remove features that do not exist
for group in feature_groups:

    feature_groups[group] = [
        f
        for f in feature_groups[group]
        if f in all_structured
    ]


# ============================================================
# 6. PRINT FEATURE GROUPS
# ============================================================

print("\n" + "=" * 70)
print("CLEAN FEATURE GROUPS")
print("=" * 70)

for group, features in feature_groups.items():

    print(
        f"\n{group}: {len(features)} features"
    )

    print(features)


# ============================================================
# 7. PREPARE STRUCTURED DATA
# ============================================================

X_train_structured = (
    train_df[all_structured]
    .replace(
        [np.inf, -np.inf],
        np.nan
    )
    .fillna(0)
)

X_test_structured = (
    test_df[all_structured]
    .replace(
        [np.inf, -np.inf],
        np.nan
    )
    .fillna(0)
)

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(
    X_train_structured
)

X_test_scaled = scaler.transform(
    X_test_structured
)


# ============================================================
# 8. EVALUATION FUNCTION
# ============================================================

def evaluate_model(
    name,
    selected_features
):

    if len(selected_features) == 0:

        X_train = X_train_text
        X_test = X_test_text

    else:

        positions = [
            all_structured.index(f)
            for f in selected_features
        ]

        X_train_selected = (
            X_train_scaled[:, positions]
        )

        X_test_selected = (
            X_test_scaled[:, positions]
        )

        X_train = hstack([
            X_train_text,
            csr_matrix(
                X_train_selected
            )
        ])

        X_test = hstack([
            X_test_text,
            csr_matrix(
                X_test_selected
            )
        ])

    model = LogisticRegression(
        max_iter=1500,
        class_weight="balanced",
        random_state=42
    )

    model.fit(
        X_train,
        y_train
    )

    predictions = model.predict(
        X_test
    )

    probabilities = (
        model
        .predict_proba(X_test)[:, 1]
    )

    return {

        "Feature Set":
            name,

        "N Features":
            len(selected_features),

        "Accuracy":
            accuracy_score(
                y_test,
                predictions
            ),

        "Precision":
            precision_score(
                y_test,
                predictions,
                zero_division=0
            ),

        "Recall":
            recall_score(
                y_test,
                predictions,
                zero_division=0
            ),

        "F1":
            f1_score(
                y_test,
                predictions,
                zero_division=0
            ),

        "AUROC":
            roc_auc_score(
                y_test,
                probabilities
            )
    }


# ============================================================
# 9. INDIVIDUAL FEATURE GROUP EXPERIMENTS
# ============================================================

results = []


# TEXT ONLY
results.append(
    evaluate_model(
        "Text Only",
        []
    )
)


for group, features in feature_groups.items():

    results.append(
        evaluate_model(
            group,
            features
        )
    )


# ============================================================
# 10. IMPORTANT COMBINATIONS
# ============================================================

affective = feature_groups[
    "Affective/Psychological"
]

social = feature_groups[
    "Social/Relationship"
]

self_reference = feature_groups[
    "Self-Reference/Pronouns"
]

cognitive = feature_groups[
    "Cognitive/Psycholinguistic"
]

temporal = feature_groups[
    "Temporal/Attention"
]

engagement = feature_groups[
    "Social-Media Engagement"
]


# Affective + Social
results.append(
    evaluate_model(
        "Affective + Social",
        sorted(
            list(
                set(
                    affective +
                    social
                )
            )
        )
    )
)


# Affective + Self-reference
results.append(
    evaluate_model(
        "Affective + Self-Reference",
        sorted(
            list(
                set(
                    affective +
                    self_reference
                )
            )
        )
    )
)


# Affective + Cognitive
results.append(
    evaluate_model(
        "Affective + Cognitive",
        sorted(
            list(
                set(
                    affective +
                    cognitive
                )
            )
        )
    )
)


# Affective + Social + Self-reference
results.append(
    evaluate_model(
        "Affective + Social + Self-Reference",
        sorted(
            list(
                set(
                    affective +
                    social +
                    self_reference
                )
            )
        )
    )
)


# Affective + Social + Engagement
results.append(
    evaluate_model(
        "Affective + Social + Engagement",
        sorted(
            list(
                set(
                    affective +
                    social +
                    engagement
                )
            )
        )
    )
)


# ALL CLEAN GROUPS
all_clean_features = sorted(
    list(
        set(
            feature
            for features
            in feature_groups.values()
            for feature in features
        )
    )
)

results.append(
    evaluate_model(
        "All Clean Structured Features",
        all_clean_features
    )
)


# ============================================================
# 11. RESULTS TABLE
# ============================================================

results_df = pd.DataFrame(
    results
)

metrics = [
    "Accuracy",
    "Precision",
    "Recall",
    "F1",
    "AUROC"
]

results_df[metrics] = (
    results_df[metrics]
    .round(4)
)

results_df = (
    results_df
    .sort_values(
        "AUROC",
        ascending=False
    )
    .reset_index(drop=True)
)


print("\n" + "=" * 70)
print("CLEAN FEATURE ABLATION RESULTS")
print("=" * 70)

display(
    results_df
)


# ============================================================
# 12. IMPROVEMENT OVER TEXT BASELINE
# ============================================================

baseline = results_df.loc[
    results_df["Feature Set"]
    == "Text Only",
    "AUROC"
].iloc[0]

results_df[
    "AUROC Improvement"
] = (
    results_df["AUROC"] -
    baseline
).round(4)


print("\n" + "=" * 70)
print("IMPROVEMENT OVER TEXT-ONLY BASELINE")
print("=" * 70)

display(
    results_df[
        [
            "Feature Set",
            "N Features",
            "AUROC",
            "AUROC Improvement"
        ]
    ]
    .sort_values(
        "AUROC Improvement",
        ascending=False
    )
    .reset_index(drop=True)
)


# ============================================================
# 13. SAVE RESULTS
# ============================================================

results_df.to_csv(
    "/content/dreaddit_clean_ablation.csv",
    index=False
)

print(
    "\nSaved results to:"
)

print(
    "/content/dreaddit_clean_ablation.csv"
)

print("\n" + "=" * 70)
print("CLEAN ABLATION STUDY COMPLETE")
print("=" * 70)

======================================================================
LOADING DREADDIT DATASET
======================================================================
Using Colab cache for faster access to the 'stress-analysis-in-social-media' dataset.

Creating TF-IDF features...
TF-IDF shape: (2838, 30000)

Number of usable structured features: 108

======================================================================
CLEAN FEATURE GROUPS
======================================================================

Affective/Psychological: 12 features
['lex_liwc_Tone', 'lex_liwc_affect', 'lex_liwc_posemo', 'lex_liwc_negemo', 'lex_liwc_anx', 'lex_liwc_anger', 'lex_liwc_sad', 'lex_liwc_feel', 'lex_liwc_health', 'lex_liwc_risk', 'lex_liwc_death', 'sentiment']

Cognitive/Psycholinguistic: 10 features
['lex_liwc_Analytic', 'lex_liwc_Clout', 'lex_liwc_Authentic', 'lex_liwc_cogproc', 'lex_liwc_insight', 'lex_liwc_cause', 'lex_liwc_discrep', 'lex_liwc_tentat', 'lex_liwc_certain', 'lex_liwc_differ']

Self-Reference/Pronouns: 8 features
['lex_liwc_i', 'lex_liwc_we', 'lex_liwc_you', 'lex_liwc_shehe', 'lex_liwc_they', 'lex_liwc_ppron', 'lex_liwc_pronoun', 'lex_liwc_ipron']

Social/Relationship: 9 features
['lex_liwc_social', 'lex_liwc_family', 'lex_liwc_friend', 'lex_liwc_affiliation', 'lex_liwc_female', 'lex_liwc_male', 'lex_liwc_power', 'lex_liwc_reward', 'lex_liwc_achieve']

Temporal/Attention: 3 features
['lex_liwc_focuspast', 'lex_liwc_focuspresent', 'lex_liwc_focusfuture']

Social-Media Engagement: 3 features
['social_karma', 'social_upvote_ratio', 'social_num_comments']

Basic Language: 18 features
['lex_liwc_WC', 'lex_liwc_WPS', 'lex_liwc_Dic', 'lex_liwc_function', 'lex_liwc_pronoun', 'lex_liwc_article', 'lex_liwc_prep', 'lex_liwc_auxverb', 'lex_liwc_adverb', 'lex_liwc_conj', 'lex_liwc_negate', 'lex_liwc_verb', 'lex_liwc_adj', 'lex_liwc_compare', 'lex_liwc_interrog', 'lex_liwc_number', 'lex_liwc_quant', 'lex_liwc_Sixltr']

DAL Lexical: 9 features
['lex_dal_max_pleasantness', 'lex_dal_max_activation', 'lex_dal_max_imagery', 'lex_dal_min_pleasantness', 'lex_dal_min_activation', 'lex_dal_min_imagery', 'lex_dal_avg_activation', 'lex_dal_avg_imagery', 'lex_dal_avg_pleasantness']

Syntax: 2 features
['syntax_ari', 'syntax_fk_grade']

======================================================================
CLEAN FEATURE ABLATION RESULTS
======================================================================

,Feature Set,N Features,Accuracy,Precision,Recall,F1,AUROC
0,Affective + Social + Engagement,24,0.7622,0.7571,0.7940,0.7751,0.8586
1,Affective/Psychological,12,0.7692,0.7615,0.8049,0.7826,0.8581
2,Affective + Cognitive,22,0.7720,0.7655,0.8049,0.7847,0.8560
3,Affective + Social,21,0.7650,0.7610,0.7940,0.7772,0.8557
4,Affective + Self-Reference,20,0.7706,0.7635,0.8049,0.7836,0.8519
5,Affective + Social + Self-Reference,29,0.7692,0.7713,0.7859,0.7785,0.8499
6,All Clean Structured Features,73,0.7608,0.7565,0.7913,0.7735,0.8433
7,Social-Media Engagement,3,0.7427,0.7307,0.7940,0.7610,0.8250
8,Text Only,0,0.7161,0.7096,0.7615,0.7346,0.8205
9,Syntax,2,0.7203,0.7056,0.7859,0.7436,0.8187
10,Social/Relationship,9,0.7049,0.6917,0.7724,0.7298,0.8079
11,DAL Lexical,9,0.7035,0.6977,0.7507,0.7232,0.8048
12,Temporal/Attention,3,0.7063,0.7054,0.7398,0.7222,0.8030
13,Cognitive/Psycholinguistic,10,0.7161,0.7065,0.7696,0.7367,0.7987
14,Self-Reference/Pronouns,8,0.7231,0.7070,0.7913,0.7468,0.7955
15,Basic Language,18,0.7007,0.6904,0.7615,0.7242,0.7828

======================================================================
IMPROVEMENT OVER TEXT-ONLY BASELINE
======================================================================

                            Feature Set  N Features   AUROC  AUROC Improvement
0       Affective + Social + Engagement          24  0.8586             0.0381
1               Affective/Psychological          12  0.8581             0.0376
2                 Affective + Cognitive          22  0.8560             0.0355
3                    Affective + Social          21  0.8557             0.0352
4            Affective + Self-Reference          20  0.8519             0.0314
5   Affective + Social + Self-Reference          29  0.8499             0.0294
6         All Clean Structured Features          73  0.8433             0.0228
7               Social-Media Engagement           3  0.8250             0.0045
8                             Text Only           0  0.8205             0.0000
9                                Syntax           2  0.8187            -0.0018
10                  Social/Relationship           9  0.8079            -0.0126
11                          DAL Lexical           9  0.8048            -0.0157
12                   Temporal/Attention           3  0.8030            -0.0175
13           Cognitive/Psycholinguistic          10  0.7987            -0.0218
14              Self-Reference/Pronouns           8  0.7955            -0.0250
15                       Basic Language          18  0.7828            -0.0377

Saved results to:
/content/dreaddit_clean_ablation.csv

======================================================================
CLEAN ABLATION STUDY COMPLETE
======================================================================